INSERT INTO Users (Login, Password, Name, Adress) VALUES ('one', 'pass', 'Andrew', 'Saratov');

CREATE TABLE dates (d DATE);

INSERT INTO dates (d) VALUES ('06.27.2016 15:49:26');
INSERT INTO dates (d) VALUES (SYSDATE);
SELECT TO_CHAR(d, 'DD.MM.YYYY HH24:MI:SS') FROM DATES;

SELECT * FROM Products;

SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'DD.MM.YYYY HH24:MI:SS') FROM DUAL;

UPDATE Products
SET name = 'tttttttttttt'
WHERE id = 9;

SELECT * FROM USERS;