SELECT * FROM Products;
SELECT * FROM Users;
SELECT * FROM Bids;

INSERT INTO Users (LOGIN, PASSWORD, NAME, ADDRESS) VALUES ('koshi', 'a753159', 'Koshi', 'London');
DELETE FROM Users WHERE LOGIN = 'koshi';

INSERT INTO Bids (ID, USERLOGIN, PRODUCTID, BID) VALUES (bids_seq.nextval, 'koshi', '2', 1100);

SELECT MAX(BID) FROM (SELECT * FROM Bids WHERE Bids.PRODUCTID = 3);

SELECT * FROM Bids WHERE BID IN (SELECT MAX(BID) FROM Bids) AND PRODUCTID = 3;

SELECT * FROM Products 
WHERE PRICE LIKE lower('%Mixer%');