DROP SEQUENCE  users_seq;
DROP SEQUENCE  products_seq;
DROP SEQUENCE  bids_seq;
/*SEQUENCES*/
/*For Users*/
CREATE SEQUENCE users_seq
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

/*For Products*/
CREATE SEQUENCE products_seq
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

/*For Bids*/
CREATE SEQUENCE bids_seq
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;